from selenium import webdriver
from selenium.webdriver.support.select import Select
from config import CONFIG
from signatureImport import signatures
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
import time, login, os, sys
import logging

script = "Signatures_yara.py.log"
logging.basicConfig(filename='./files/test_logs/%s.log' % script, format='%(asctime)s - %(levelname)s - %(message)s', level=logging.INFO)
logger = logging.getLogger('test')

if CONFIG.WEBDRIVER == "Chrome":
    _chrome_options = Options()
    _chrome_options.add_argument('--start-fullscreen')
    driver = webdriver.Chrome(chrome_options=_chrome_options)

elif CONFIG.WEBDRIVER == "Firefox":

    driver = webdriver.Firefox()

else:

    logger.warning('No valid Webdrive was provided. ')

# driver.set_window_size(1440, 1200)
driver.implicitly_wait(CONFIG.waittime)
# time.sleep(2)

host = CONFIG.HOST

cwd = os.getcwd()

sigs = ["files/Signatures/Yara/Android_adware.yar",
        "files/Signatures/Yara/Android_AliPay_smsStealer.yar",
        "files/Signatures/Yara/Android_Amtrckr_20160519.yar",
        "files/Signatures/Yara/Antidebug_AntiVM_index.yar",
        "files/Signatures/Yara/Android_ASSDdeveloper.yar",
        "files/Signatures/Yara/Android_AVITOMMS.yar",
        "files/Signatures/Yara/Android_Backdoor_script.yar",
        "files/Signatures/Yara/Android_Backdoor.yar",
        "files/Signatures/Yara/Android_BadMirror.yar",
        "files/Signatures/Yara/Android_Banker_Acecard.yar",
        "files/Signatures/Yara/Android_BatteryBot_ClickFraud.yar",
        "files/Signatures/Yara/Android_Clicker_G.yar",
        "files/Signatures/Yara/Android_Copy9.yar",
        "files/Signatures/Yara/Android_DeathRing.yar",
        "files/Signatures/Yara/Android_Dectus_rswm.yar",
        "files/Signatures/Yara/Android_Dendroid_RAT.yar",
        "files/Signatures/Yara/Android_Dogspectus.yar",
        "files/Signatures/Yara/Android_FakeApps.yar",
        "files/Signatures/Yara/Android_FakeBank_Fanta.yar",
        "files/Signatures/Yara/Android_generic_adware.yar",
        "files/Signatures/Yara/Android_generic_smsfraud.yar",
        "files/Signatures/Yara/Android_Godless.yar",
        "files/Signatures/Yara/Android_HackintTeam_Implant.yar",
        "files/Signatures/Yara/Android_Libyan_Scorpions.yar",
        "files/Signatures/Yara/Android_malware_Advertising.yar",
        "files/Signatures/Yara/Android_malware_banker.yar",
        "files/Signatures/Yara/Android_malware_ChinesePorn.yar",
        "files/Signatures/Yara/Android_malware_Dropper.yar",
        "files/Signatures/Yara/Android_malware_Fake_MosKow.yar",
        "files/Signatures/Yara/Android_malware_HackingTeam.yar",
        "files/Signatures/Yara/Android_Malware_Ramsonware.yar",
        "files/Signatures/Yara/Android_malware_SMSsender.yar",
        "files/Signatures/Yara/Android_Malware_Tinhvan.yar",
        "files/Signatures/Yara/Android_Malware_Towelroot.yar",
        "files/Signatures/Yara/Android_malware_xbot007.yar",
        "files/Signatures/Yara/Android_MalwareCertificates.yar",
        "files/Signatures/Yara/Android_mapin.yar",
        "files/Signatures/Yara/Android_Marcher_2.yar",
        "files/Signatures/Yara/Android_MazarBot_z.yar",
        "files/Signatures/Yara/Android_Metasploit_Payload.yar",
        "files/Signatures/Yara/Android_Metasploit.yar",
        "files/Signatures/Yara/Android_OmniRat.yar",
        "files/Signatures/Yara/Android_Overlayer.yar",
        "files/Signatures/Yara/Android_Pink_Locker.yar",
        "files/Signatures/Yara/Android_Polish_Bankbot.yar",
        "files/Signatures/Yara/Android_pornClicker.yar",
        "files/Signatures/Yara/Android_RuMMS.yar",
        "files/Signatures/Yara/Android_SandroRat.yar",
        "files/Signatures/Yara/Android_sk_bankTr.yar",
        "files/Signatures/Yara/Android_SlemBunk.yar",
        "files/Signatures/Yara/Android_SMSFraud.yar",
        "files/Signatures/Yara/Android_SpyAgent.yar",
        "files/Signatures/Yara/Android_Spynet.yar",
        "files/Signatures/Yara/Android_SpyNote.yar",
        "files/Signatures/Yara/Android_Spywaller.yar",
        "files/Signatures/Yara/Android_Switcher.yar",
        "files/Signatures/Yara/Android_Tachi.yar",
        "files/Signatures/Yara/Android_Tempting_Cedar_Spyware.yar",
        "files/Signatures/Yara/Android_Tordow.yar",
        "files/Signatures/Yara/Android_Triada_Banking.yar",
        "files/Signatures/Yara/Android_Trojan_Dendroid.yar",
        "files/Signatures/Yara/Android_Trojan_Droidjack.yar",
        "files/Signatures/Yara/Android_VikingOrder.yar",
        "files/Signatures/Yara/Android_VirusPolicia.yar",
        "files/Signatures/Yara/APT_APT10.yar",
        "files/Signatures/Yara/APT_APT15.yar",
        "files/Signatures/Yara/APT_APT17.yar",
        "files/Signatures/Yara/APT_APT29_Grizzly_Steppe.yar",
        "files/Signatures/Yara/APT_APT3102.yar",
        "files/Signatures/Yara/APT_APT9002.yar",
        "files/Signatures/Yara/APT_Backspace.yar",
        "files/Signatures/Yara/APT_Bestia.yar",
        "files/Signatures/Yara/APT_Blackenergy.yar",
        "files/Signatures/Yara/APT_Bluetermite_Emdivi.yar",
        "files/Signatures/Yara/APT_C16.yar",
        "files/Signatures/Yara/APT_Carbanak.yar",
        "files/Signatures/Yara/APT_Careto.yar",
        "files/Signatures/Yara/APT_Casper.yar",
        "files/Signatures/Yara/APT_CheshireCat.yar",
        "files/Signatures/Yara/APT_Cloudduke.yar",
        "files/Signatures/Yara/APT_Codoso.yar",
        "files/Signatures/Yara/APT_CrashOverride.yar",
        "files/Signatures/Yara/APT_DeepPanda_Anthem.yar",
        "files/Signatures/Yara/APT_DeputyDog.yar",
        "files/Signatures/Yara/APT_Derusbi.yar",
        "files/Signatures/Yara/APT_DPRK_ROKRAT.yar",
        "files/Signatures/Yara/APT_Dubnium.yar",
        "files/Signatures/Yara/APT_Emissary.yar",
        "files/Signatures/Yara/APT_EnergeticBear_backdoored_ssh.yar",
        "files/Signatures/Yara/APT_eqgrp_apr17.yar",
        "files/Signatures/Yara/APT_Equation.yar",
        "files/Signatures/Yara/APT_EQUATIONGRP.yar",
        "files/Signatures/Yara/APT_fancybear_dnc.yar",
        "files/Signatures/Yara/APT_fancybear_downdelph.yar",
        "files/Signatures/Yara/APT_FIN7.yar",
        "files/Signatures/Yara/APT_FiveEyes.yar",
        "files/Signatures/Yara/APT_furtim.yar",
        "files/Signatures/Yara/APT_FVEY_ShadowBrokers_Jan17_Screen_Strings.yar",
        "files/Signatures/Yara/APT_Grasshopper.yar",
        "files/Signatures/Yara/APT_Greenbug.yar",
        "files/Signatures/Yara/APT_Grizzlybear_uscert.yar",
        "files/Signatures/Yara/APT_HackingTeam.yar",
        "files/Signatures/Yara/APT_Hellsing.yar",
        "files/Signatures/Yara/APT_HiddenCobra.yar",
        "files/Signatures/Yara/APT_Hikit.yar",
        "files/Signatures/Yara/APT_Industroyer.yar",
        "files/Signatures/Yara/APT_Irontiger.yar",
        "files/Signatures/Yara/APT_Kaba.yar",
        "files/Signatures/Yara/APT_Ke3Chang_TidePool.yar",
        "files/Signatures/Yara/APT_KeyBoy.yar",
        "files/Signatures/Yara/APT_LotusBlossom.yar",
        "files/Signatures/Yara/APT_Minidionis.yar",
        "files/Signatures/Yara/APT_Mirage.yar",
        "files/Signatures/Yara/APT_Molerats.yar",
        "files/Signatures/Yara/APT_Mongall.yar",
        "files/Signatures/Yara/APT_NGO.yar",
        "files/Signatures/Yara/APT_Oilrig.yar",
        "files/Signatures/Yara/APT_OpClandestineWolf.yar",
        "files/Signatures/Yara/APT_OPCleaver.yar",
        "files/Signatures/Yara/APT_OpDustStorm.yar",
        "files/Signatures/Yara/APT_OpPotao.yar",
        "files/Signatures/Yara/APT_Passcv.yar",
        "files/Signatures/Yara/APT_PCclient.yar",
        "files/Signatures/Yara/APT_Pipcreat.yar",
        "files/Signatures/Yara/APT_Platinum.yar",
        "files/Signatures/Yara/APT_Poseidon_Group.yar",
        "files/Signatures/Yara/APT_Prikormka.yar",
        "files/Signatures/Yara/APT_PutterPanda.yar",
        "files/Signatures/Yara/APT_Regin.yar",
        "files/Signatures/Yara/APT_RemSec.yar",
        "files/Signatures/Yara/APT_Scarab_Scieron.yar",
        "files/Signatures/Yara/APT_Seaduke.yar",
        "files/Signatures/Yara/APT_Shamoon_StoneDrill.yar",
        "files/Signatures/Yara/APT_Snowglobe_Babar.yar",
        "files/Signatures/Yara/APT_Sofacy_Bundestag.yar",
        "files/Signatures/Yara/APT_Sofacy_Fysbis.yar",
        "files/Signatures/Yara/APT_Sofacy_Jun16.yar",
        "files/Signatures/Yara/APT_Sphinx_Moth.yar",
        "files/Signatures/Yara/APT_Stuxnet.yar",
        "files/Signatures/Yara/APT_Terracota.yar",
        "files/Signatures/Yara/APT_ThreatGroup3390.yar",
        "files/Signatures/Yara/APT_TradeSecret.yar",
        "files/Signatures/Yara/APT_Turla_Neuron.yar",
        "files/Signatures/Yara/APT_Turla_RUAG.yar",
        "files/Signatures/Yara/APT_Unit78020.yar",
        "files/Signatures/Yara/APT_UP007_SLServer.yar",
        "files/Signatures/Yara/APT_Waterbug.yar",
        "files/Signatures/Yara/APT_WildNeutron.yar",
        "files/Signatures/Yara/APT_Windigo_Onimiki.yar",
        "files/Signatures/Yara/APT_Winnti.yar",
        "files/Signatures/Yara/APT_WoolenGoldfish.yar",
        "files/Signatures/Yara/attachment.yar",
        "files/Signatures/Yara/bank_rule.yar",
        "files/Signatures/Yara/Crypto_index.yar",
        "files/Signatures/Yara/crypto_signatures.yar",
        "files/Signatures/Yara/CVE_Rules_index.yar",
        "files/Signatures/Yara/CVE-2010-0887.yar",
        "files/Signatures/Yara/CVE-2012-0158.yar",
        "files/Signatures/Yara/CVE-2013-0074.yar",
        "files/Signatures/Yara/CVE-2013-0422.yar",
        "files/Signatures/Yara/CVE-2015-1701.yar",
        "files/Signatures/Yara/CVE-2015-2426.yar",
        "files/Signatures/Yara/CVE-2015-2545.yar",
        "files/Signatures/Yara/CVE-2015-5119.yar",
        "files/Signatures/Yara/CVE-2016-5195.yar",
        "files/Signatures/Yara/CVE-2017-11882.yar",
        "files/Signatures/Yara/CVE-2018-4878.yar",
        "files/Signatures/Yara/DeltaCharlie.yara",
        "files/Signatures/Yara/domain.yar",
        "files/Signatures/Yara/DSIE-Detection_(10-15-13).yar",
        "files/Signatures/Yara/EK_Angler.yar",
        "files/Signatures/Yara/EK_Blackhole.yar",
        "files/Signatures/Yara/EK_BleedingLife.yar",
        "files/Signatures/Yara/EK_Crimepack.yar",
        "files/Signatures/Yara/EK_Eleonore.yar",
        "files/Signatures/Yara/EK_Fragus.yar",
        "files/Signatures/Yara/EK_Phoenix.yar",
        "files/Signatures/Yara/EK_Sakura.yar",
        "files/Signatures/Yara/EK_ZeroAcces.yar",
        "files/Signatures/Yara/EK_Zerox88.yar",
        "files/Signatures/Yara/EK_Zeus.yar",
        "files/Signatures/Yara/EMAIL_Cryptowall.yar",
        "files/Signatures/Yara/email_index.yar",
        "files/Signatures/Yara/email_Ukraine_BE_powerattack.yar",
        "files/Signatures/Yara/EXPERIMENTAL_Beef.yar",
        "files/Signatures/Yara/Exploit-Kits_index.yar",
        "files/Signatures/Yara/GEN_PowerShell.yar",
        "files/Signatures/Yara/general.yara",
        "files/Signatures/Yara/HotelAlfa.yara",
        "files/Signatures/Yara/image.yar",
        "files/Signatures/Yara/index_w_mobile.yar",
        "files/Signatures/Yara/index.yar",
        "files/Signatures/Yara/IndiaAlfa.yara",
        "files/Signatures/Yara/IndiaBravo.yara",
        "files/Signatures/Yara/IndiaCharlie.yara",
        "files/Signatures/Yara/IndiaDelta.yara",
        "files/Signatures/Yara/IndiaEcho.yara",
        "files/Signatures/Yara/IndiaGolf.yara",
        "files/Signatures/Yara/IndiaHotel.yara",
        "files/Signatures/Yara/IndiaJuliett.yara",
        "files/Signatures/Yara/IndiaWhiskey.yara",
        "files/Signatures/Yara/ip.yar",
        "files/Signatures/Yara/Javascript_exploit_and_obfuscation.yar",
        "files/Signatures/Yara/JJencode.yar",
        "files/Signatures/Yara/KiloAlfa.yara",
        "files/Signatures/Yara/LimaAlfa.yara",
        "files/Signatures/Yara/LimaBravo.yara",
        "files/Signatures/Yara/LimaCharlie.yara",
        "files/Signatures/Yara/LimaDelta.yara",
        "files/Signatures/Yara/magic.yar",
        "files/Signatures/Yara/Maldoc_APT_OLE_JSRat.yar",
        "files/Signatures/Yara/Maldoc_Contains_VBE_File.yar",
        "files/Signatures/Yara/Maldoc_CVE_2017_8759.yar",
        "files/Signatures/Yara/Maldoc_CVE_2017_11882.yar",
        "files/Signatures/Yara/Maldoc_CVE-2017-0199.yar",
        "files/Signatures/Yara/Maldoc_DDE.yar",
        "files/Signatures/Yara/Maldoc_Dridex.yar",
        "files/Signatures/Yara/Maldoc_Hidden_PE_file.yar",
        "files/Signatures/Yara/Maldoc_malrtf_ole2link.yar",
        "files/Signatures/Yara/Maldoc_MIME_ActiveMime_b64.yar",
        "files/Signatures/Yara/Maldoc_PDF.yar",
        "files/Signatures/Yara/Maldoc_PowerPointMouse.yar",
        "files/Signatures/Yara/maldoc_somerules.yar",
        "files/Signatures/Yara/Maldoc_Suspicious_OLE_target.yar",
        "files/Signatures/Yara/Maldoc_UserForm.yar",
        "files/Signatures/Yara/Maldoc_VBA_macro_code.yar",
        "files/Signatures/Yara/Maldoc_Word_2007_XML_Flat_OPC.yar",
        "files/Signatures/Yara/Malicious_Documents_index.yar",
        "files/Signatures/Yara/MALW_adwind_RAT.yar",
        "files/Signatures/Yara/MALW_AgentTesla_SMTP.yar",
        "files/Signatures/Yara/MALW_AgentTesla.yar",
        "files/Signatures/Yara/MALW_Alina.yar",
        "files/Signatures/Yara/MALW_Andromeda.yar",
        "files/Signatures/Yara/MALW_Athena.yar",
        "files/Signatures/Yara/MALW_Atmos.yar",
        "files/Signatures/Yara/MALW_AZORULT.yar",
        "files/Signatures/Yara/MALW_BackdoorSSH.yar",
        "files/Signatures/Yara/MALW_Backoff.yar",
        "files/Signatures/Yara/MALW_Bangat.yar",
        "files/Signatures/Yara/MALW_Batel.yar",
        "files/Signatures/Yara/MALW_BlackRev.yar",
        "files/Signatures/Yara/MALW_BlackWorm.yar",
        "files/Signatures/Yara/MALW_Boouset.yar",
        "files/Signatures/Yara/MALW_Bublik.yar",
        "files/Signatures/Yara/MALW_Buzus_Softpulse.yar",
        "files/Signatures/Yara/MALW_CAP_HookExKeylogger.yar",
        "files/Signatures/Yara/MALW_CAP_Win32Inet.yara",
        "files/Signatures/Yara/MALW_Chicken.yar",
        "files/Signatures/Yara/MALW_Citadel.yar",
        "files/Signatures/Yara/MALW_Cloaking.yar",
        "files/Signatures/Yara/MALW_Cookies.yar",
        "files/Signatures/Yara/MALW_Corkow.yar",
        "files/Signatures/Yara/MALW_Cxpid.yar",
        "files/Signatures/Yara/MALW_Cythosia.yar",
        "files/Signatures/Yara/MALW_DDoSTf.yar",
        "files/Signatures/Yara/MALW_Derkziel.yar",
        "files/Signatures/Yara/MALW_Dexter.yar",
        "files/Signatures/Yara/MALW_DiamondFox.yar",
        "files/Signatures/Yara/MALW_DirtJumper.yar",
        "files/Signatures/Yara/MALW_Elex.yar",
        "files/Signatures/Yara/MALW_Elknot.yar",
        "files/Signatures/Yara/MALW_Emotet.yar",
        "files/Signatures/Yara/MALW_Empire.yar",
        "files/Signatures/Yara/MALW_Enfal.yar",
        "files/Signatures/Yara/MALW_Exploit_UAC_Elevators.yar",
        "files/Signatures/Yara/MALW_Ezcob.yar",
        "files/Signatures/Yara/MALW_F0xy.yar",
        "files/Signatures/Yara/MALW_FakeM.yar",
        "files/Signatures/Yara/MALW_FALLCHILL.yar",
        "files/Signatures/Yara/MALW_Fareit.yar",
        "files/Signatures/Yara/MALW_Favorite.yar",
        "files/Signatures/Yara/MALW_Furtim.yar",
        "files/Signatures/Yara/MALW_Gafgyt.yar",
        "files/Signatures/Yara/MALW_Genome.yar",
        "files/Signatures/Yara/MALW_Glasses.yar",
        "files/Signatures/Yara/MALW_Gozi.yar",
        "files/Signatures/Yara/MALW_Grozlex.yar",
        "files/Signatures/Yara/MALW_Hajime.yar",
        "files/Signatures/Yara/MALW_Hsdfihdf_banking.yar",
        "files/Signatures/Yara/MALW_Httpsd_ELF.yar",
        "files/Signatures/Yara/MALW_IcedID.yar",
        "files/Signatures/Yara/MALW_Iexpl0ree.yar",
        "files/Signatures/Yara/MALW_IMuler.yar",
        "files/Signatures/Yara/MALW_Install11.yar",
        "files/Signatures/Yara/MALW_Intel_Virtualization.yar",
        "files/Signatures/Yara/MALW_IotReaper.yar",
        "files/Signatures/Yara/MALW_Jolob_Backdoor.yar",
        "files/Signatures/Yara/MALW_Kelihos.yar",
        "files/Signatures/Yara/MALW_KINS.yar",
        "files/Signatures/Yara/MALW_Korlia.yar",
        "files/Signatures/Yara/MALW_Korplug.yar",
        "files/Signatures/Yara/MALW_Kovter.yar",
        "files/Signatures/Yara/MALW_Kraken.yar",
        "files/Signatures/Yara/MALW_Kwampirs.yar",
        "files/Signatures/Yara/MALW_Lateral_Movement.yar",
        "files/Signatures/Yara/MALW_Lenovo_Superfish.yar",
        "files/Signatures/Yara/MALW_LinuxBew.yar",
        "files/Signatures/Yara/MALW_LinuxHelios.yar",
        "files/Signatures/Yara/MALW_LinuxMoose.yar",
        "files/Signatures/Yara/MALW_LostDoor.yar",
        "files/Signatures/Yara/MALW_LuaBot.yar",
        "files/Signatures/Yara/MALW_LuckyCat.yar",
        "files/Signatures/Yara/MALW_LURK0.yar",
        "files/Signatures/Yara/MALW_MacControl.yar",
        "files/Signatures/Yara/MALW_Madness.yar",
        "files/Signatures/Yara/MALW_Magento_backend.yar",
        "files/Signatures/Yara/MALW_Magento_frontend.yar",
        "files/Signatures/Yara/MALW_Magento_suspicious.yar",
        "files/Signatures/Yara/MALW_Mailers.yar",
        "files/Signatures/Yara/MALW_Miancha.yar",
        "files/Signatures/Yara/MALW_MiniAsp3_mem.yar",
        "files/Signatures/Yara/MALW_Mirai_Okiru_ELF.yar",
        "files/Signatures/Yara/MALW_Mirai_Satori_ELF.yar",
        "files/Signatures/Yara/MALW_Mirai.yar",
        "files/Signatures/Yara/MALW_Miscelanea_Linux.yar",
        "files/Signatures/Yara/MALW_Miscelanea.yar",
        "files/Signatures/Yara/MALW_Monero_Miner_installer.yar",
        "files/Signatures/Yara/MALW_Naikon.yar",
        "files/Signatures/Yara/MALW_Naspyupdate.yar",
        "files/Signatures/Yara/MALW_NetTraveler.yar",
        "files/Signatures/Yara/MALW_NionSpy.yar",
        "files/Signatures/Yara/MALW_Notepad.yar",
        "files/Signatures/Yara/MALW_NSFree.yar",
        "files/Signatures/Yara/MALW_Odinaff.yar",
        "files/Signatures/Yara/MALW_Olyx.yar",
        "files/Signatures/Yara/MALW_OSX_Leverage.yar",
        "files/Signatures/Yara/MALW_PE_sections.yar",
        "files/Signatures/Yara/MALW_PittyTiger.yar",
        "files/Signatures/Yara/MALW_Ponmocup.yar",
        "files/Signatures/Yara/MALW_Pony.yar",
        "files/Signatures/Yara/MALW_PubSab.yar",
        "files/Signatures/Yara/MALW_Pyinstaller.yar",
        "files/Signatures/Yara/MALW_PyPI.yar",
        "files/Signatures/Yara/MALW_Quarian.yar",
        "files/Signatures/Yara/MALW_Rebirth_Vulcan_ELF.yar",
        "files/Signatures/Yara/MALW_Regsubdat.yar",
        "files/Signatures/Yara/MALW_Retefe.yar",
        "files/Signatures/Yara/MALW_Rockloader.yar",
        "files/Signatures/Yara/MALW_Rooter.yar",
        "files/Signatures/Yara/MALW_Rovnix.yar",
        "files/Signatures/Yara/MALW_Safenet.yar",
        "files/Signatures/Yara/MALW_Sakurel.yar",
        "files/Signatures/Yara/MALW_Sayad.yar",
        "files/Signatures/Yara/MALW_Scarhikn.yar",
        "files/Signatures/Yara/MALW_Sendsafe.yar",
        "files/Signatures/Yara/MALW_Shamoon.yar",
        "files/Signatures/Yara/MALW_Shifu.yar",
        "files/Signatures/Yara/MALW_sitrof_fortis_scar.yar",
        "files/Signatures/Yara/MALW_Skeleton.yar",
        "files/Signatures/Yara/MALW_Spora.yar",
        "files/Signatures/Yara/MALW_Sqlite.yar",
        "files/Signatures/Yara/MALW_Stealer.yar",
        "files/Signatures/Yara/MALW_Surtr.yar",
        "files/Signatures/Yara/MALW_T5000.yar",
        "files/Signatures/Yara/MALW_Tedroo.yar",
        "files/Signatures/Yara/MALW_Tinba.yar",
        "files/Signatures/Yara/MALW_TinyShell_Backdoor_gen.yar",
        "files/Signatures/Yara/MALW_Torte_ELF.yar",
        "files/Signatures/Yara/MALW_TreasureHunt.yar",
        "files/Signatures/Yara/MALW_TrickBot.yar",
        "files/Signatures/Yara/MALW_TRITON_HATMAN.yar",
        "files/Signatures/Yara/MALW_TRITON_ICS_FRAMEWORK.yar",
        "files/Signatures/Yara/MALW_Trumpbot.yar",
        "files/Signatures/Yara/MALW_Upatre.yar",
        "files/Signatures/Yara/MALW_Urausy.yar",
        "files/Signatures/Yara/MALW_Vidgrab.yar",
        "files/Signatures/Yara/MALW_viotto_keylogger.yar",
        "files/Signatures/Yara/MALW_Virut_FileInfector_UNK_VERSION.yar",
        "files/Signatures/Yara/MALW_Volgmer.yar",
        "files/Signatures/Yara/MALW_Wabot.yar",
        "files/Signatures/Yara/MALW_Warp.yar",
        "files/Signatures/Yara/MALW_Wimmie.yar",
        "files/Signatures/Yara/MALW_xDedic_marketplace.yar",
        "files/Signatures/Yara/MALW_XHide.yar",
        "files/Signatures/Yara/MALW_XMRIG_Miner.yar",
        "files/Signatures/Yara/MALW_XOR_DDos.yar",
        "files/Signatures/Yara/MALW_Yayih.yar",
        "files/Signatures/Yara/MALW_Zegost.yar",
        "files/Signatures/Yara/MALW_Zeus.yar",
        "files/Signatures/Yara/malware_index.yar",
        "files/Signatures/Yara/Mobile_Malware_index.yar",
        "files/Signatures/Yara/packer_compiler_signatures.yar",
        "files/Signatures/Yara/packer.yar",
        "files/Signatures/Yara/Packers_index.yar",
        "files/Signatures/Yara/PapaAlfa.yara",
        "files/Signatures/Yara/peid.yar",
        "files/Signatures/Yara/POS_Bernhard.yar",
        "files/Signatures/Yara/POS_BruteforcingBot.yar",
        "files/Signatures/Yara/POS_Easterjack.yar",
        "files/Signatures/Yara/POS_FastPOS.yar",
        "files/Signatures/Yara/POS_LogPOS.yar",
        "files/Signatures/Yara/POS_MalumPOS.yar",
        "files/Signatures/Yara/POS_Mozart.yar",
        "files/Signatures/Yara/POS.yar",
        "files/Signatures/Yara/RANSOM_.CRYPTXXX.yar",
        "files/Signatures/Yara/RANSOM_777.yar",
        "files/Signatures/Yara/RANSOM_Alpha.yar",
        "files/Signatures/Yara/RANSOM_BadRabbit.yar",
        "files/Signatures/Yara/RANSOM_Cerber.yar",
        "files/Signatures/Yara/RANSOM_Comodosec.yar",
        "files/Signatures/Yara/RANSOM_Crypren.yar",
        "files/Signatures/Yara/RANSOM_Cryptolocker.yar",
        "files/Signatures/Yara/RANSOM_DMALocker.yar",
        "files/Signatures/Yara/RANSOM_DoublePulsar_Petya.yar",
        "files/Signatures/Yara/RANSOM_Erebus.yar",
        "files/Signatures/Yara/RANSOM_GoldenEye.yar",
        "files/Signatures/Yara/RANSOM_GPGQwerty.yar",
        "files/Signatures/Yara/RANSOM_Locky.yar",
        "files/Signatures/Yara/RANSOM_MS17-010_Wannacrypt.yar",
        "files/Signatures/Yara/RANSOM_PetrWrap.yar",
        "files/Signatures/Yara/RANSOM_Petya.yar",
        "files/Signatures/Yara/RANSOM_SamSam.yar",
        "files/Signatures/Yara/RANSOM_Satana.yar",
        "files/Signatures/Yara/RANSOM_Sigma.yar",
        "files/Signatures/Yara/RANSOM_Stampado.yar",
        "files/Signatures/Yara/RANSOM_TeslaCrypt.yar",
        "files/Signatures/Yara/RANSOM_Tox.yar",
        "files/Signatures/Yara/RAT_Adwind.yar",
        "files/Signatures/Yara/RAT_Adzok.yar",
        "files/Signatures/Yara/RAT_BlackShades.yar",
        "files/Signatures/Yara/RAT_Bolonyokte.yar",
        "files/Signatures/Yara/RAT_Bozok.yar",
        "files/Signatures/Yara/RAT_Cerberus.yar",
        "files/Signatures/Yara/RAT_Crimson.yar",
        "files/Signatures/Yara/RAT_CrossRAT.yar",
        "files/Signatures/Yara/RAT_CyberGate.yar",
        "files/Signatures/Yara/RAT_DarkComet.yar",
        "files/Signatures/Yara/RAT_FlyingKitten.yar",
        "files/Signatures/Yara/RAT_Gh0st.yar",
        "files/Signatures/Yara/RAT_Gholee.yar",
        "files/Signatures/Yara/RAT_Glass.yar",
        "files/Signatures/Yara/RAT_Havex.yar",
        "files/Signatures/Yara/RAT_Hizor.yar",
        "files/Signatures/Yara/RAT_Indetectables.yar",
        "files/Signatures/Yara/RAT_Inocnation.yar",
        "files/Signatures/Yara/RAT_jRAT.yar",
        "files/Signatures/Yara/RAT_Meterpreter_Reverse_Tcp.yar",
        "files/Signatures/Yara/RAT_Nanocore.yar",
        "files/Signatures/Yara/RAT_NetwiredRC.yar",
        "files/Signatures/Yara/RAT_Njrat.yar",
        "files/Signatures/Yara/RAT_PlugX.yar",
        "files/Signatures/Yara/RAT_PoisonIvy.yar",
        "files/Signatures/Yara/RAT_Ratdecoders.yar",
        "files/Signatures/Yara/RAT_Sakula.yar",
        "files/Signatures/Yara/RAT_ShadowTech.yar",
        "files/Signatures/Yara/RAT_Shim.yar",
        "files/Signatures/Yara/RAT_Terminator.yar",
        "files/Signatures/Yara/RAT_xRAT.yar",
        "files/Signatures/Yara/RAT_xRAT20.yar",
        "files/Signatures/Yara/RAT_Xtreme.yar",
        "files/Signatures/Yara/RAT_ZoxPNG.yar",
        "files/Signatures/Yara/RomeoAlfa.yara",
        "files/Signatures/Yara/RomeoBravo.yara",
        "files/Signatures/Yara/RomeoCharlie.yara",
        "files/Signatures/Yara/RomeoDelta.yara",
        "files/Signatures/Yara/RomeoEcho.yara",
        "files/Signatures/Yara/RomeoFoxtrot_mod.yara.error",
        "files/Signatures/Yara/RomeoGolf_mod.yara",
        "files/Signatures/Yara/RomeoHotel.yara",
        "files/Signatures/Yara/RomeoWhiskey.yara",
        "files/Signatures/Yara/scam.yar",
        "files/Signatures/Yara/sharedcode.yara",
        "files/Signatures/Yara/SierraAlfa.yara",
        "files/Signatures/Yara/SierraBravo.yara",
        "files/Signatures/Yara/SierraCharlie.yara",
        "files/Signatures/Yara/SierraJuliettMikeOne.yara",
        "files/Signatures/Yara/SierraJuliettMikeTwo.yara",
        "files/Signatures/Yara/suicidescripts.yara",
        "files/Signatures/Yara/suspicious_strings.yar",
        "files/Signatures/Yara/TangoAlfa.yara",
        "files/Signatures/Yara/TangoBravo.yara",
        "files/Signatures/Yara/TOOLKIT_Chinese_Hacktools.yar",
        "files/Signatures/Yara/TOOLKIT_Dubrute.yar",
        "files/Signatures/Yara/TOOLKIT_exe2hex_payload.yar",
        "files/Signatures/Yara/TOOLKIT_FinFisher_.yar",
        "files/Signatures/Yara/TOOLKIT_Gen_powerkatz.yar",
        "files/Signatures/Yara/TOOLKIT_Mandibule.yar",
        "files/Signatures/Yara/TOOLKIT_PassTheHash.yar",
        "files/Signatures/Yara/TOOLKIT_Powerstager.yar",
        "files/Signatures/Yara/TOOLKIT_Pwdump.yar",
        "files/Signatures/Yara/TOOLKIT_THOR_HackTools.yar",
        "files/Signatures/Yara/TOOLKIT_Wineggdrop.yar",
        "files/Signatures/Yara/UniformAlfa.yara",
        "files/Signatures/Yara/UniformJuliett.yara",
        "files/Signatures/Yara/url.yar",
        "files/Signatures/Yara/urls.yar",
        "files/Signatures/Yara/virustotal.yar",
        "files/Signatures/Yara/Webshells_index.yar",
        "files/Signatures/Yara/WhiskeyAlfa.yara",
        "files/Signatures/Yara/WhiskeyBravo_mod.yara",
        "files/Signatures/Yara/WhiskeyCharlie.yara",
        "files/Signatures/Yara/WhiskeyDelta.yara",
        "files/Signatures/Yara/WShell_APT_Laudanum.yar",
        "files/Signatures/Yara/Wshell_ChineseSpam.yar",
        "files/Signatures/Yara/Wshell_fire2013.yar",
        "files/Signatures/Yara/WShell_PHP_Anuna.yar",
        "files/Signatures/Yara/WShell_PHP_in_images.yar",
        "files/Signatures/Yara/WShell_THOR_Webshells.yar",
        "files/Signatures/Yara/BinaryPig_Jason_Trost.txt",
        "files/Signatures/Yara/OSINT_sigs_TJones.yara.txt",
        "files/Signatures/Yara/packers-yara.txt",
        "files/Signatures/Yara/YARA_2yearcollection.txt",
        "files/Signatures/Yara/Yara_metadata.txt",
        "files/Signatures/Yara/000_common_rules.yar",
        "files/Signatures/Yara/antidebug_antivm.yar",
        "files/Signatures/Yara/APT_APT1.yar",
        "files/Signatures/Yara/base64.yar",
        "files/Signatures/Yara/cert_wiper.yara",
        "files/Signatures/Yara/CVE-2010-0805.yar",
        "files/Signatures/Yara/CVE-2010-1297.yar",
        "files/Signatures/Yara/Android_fake_mario_app",
        "files/Signatures/Yara/APT_MoonlightMaze",
        "files/Signatures/Yara/APT_RedLeaves",
        "files/Signatures/Yara/APT_Sauron",
        "files/Signatures/Yara/APT_Sauron_extras",
        "files/Signatures/Yara/Email_fake_it_maintenance_bulletin",
        "files/Signatures/Yara/Email_generic_phishing",
        "files/Signatures/Yara/Email_quota_limit_warning",
        "files/Signatures/Yara/Maldoc_hancitor_dropper",
        "files/Signatures/Yara/MALW_Eicar",
        "files/Signatures/Yara/MALW_kirbi_mimikatz",
        "files/Signatures/Yara/MALW_PolishBankRat",
        "files/Signatures/Yara/MALW_shifu_shiz",
        "files/Signatures/Yara/mastersig",
        "files/Signatures/Yara/RANSOM_Petya_MS17_010",
        "files/Signatures/Yara/RAT_Orcus"
        ]

# Run test steps here

login(logger, host, driver, usr=CONFIG.USER[0], pssword=CONFIG.USER[1], SAML=CONFIG.SAML)

time.sleep(1)

count = 1

"""# report the cookie
cookies = driver.get_cookies()
for cookie in cookies:
    print cookie
"""
logger.info("Start Yara import test")

for signature in sigs:

    signType = "YARA"
    time.sleep(2)

    signat = cwd + os.sep + signature

    print (signat)

    try:
        status = signatures(logger, driver, signType, signat)
    except Exception as e:
        logger.critical('%s: %s', e, signat)
        driver.get(host)
        time.sleep(4)

    count += 1
    # print count
    if CONFIG.LONGRUN:

        time.sleep(1200)

    if count % 30 == 0:

        login.logout(logger, driver)
        time.sleep(1)
        login.login(logger, host, driver, usr=CONFIG.USER[0], pssword=CONFIG.USER[1])
        """
        # report the cookie
        cookies = driver.get_cookies()
        for cookie in cookies:
            print cookie
        """

logger.info("End Yara import test")

# close the browser window
driver.quit()
